# Generated by Django 3.1.7 on 2021-03-04 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('CreatedDate', models.DateTimeField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('CreatedBy', models.CharField(max_length=100)),
                ('ModifiedDate', models.DateTimeField(max_length=50)),
                ('ModifiedBy', models.DateTimeField(max_length=50)),
                ('Gender', models.CharField(max_length=50)),
                ('Active', models.BooleanField(default=False)),
                ('MobileNo', models.IntegerField(max_length=10)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('isActive', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
