# Generated by Django 3.1.7 on 2021-03-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='account',
            name='createdBy',
        ),
        migrations.RemoveField(
            model_name='account',
            name='isActive',
        ),
        migrations.AlterField(
            model_name='account',
            name='MobileNo',
            field=models.IntegerField(),
        ),
    ]
