# Generated by Django 3.1.7 on 2021-03-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0002_auto_20210304_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='ModifiedBy',
            field=models.CharField(max_length=50),
        ),
    ]
