# Generated by Django 3.1.7 on 2021-03-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0006_auto_20210322_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='MobileNo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
