# Generated by Django 3.1.7 on 2021-03-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0010_auto_20210322_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='CreatedBy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='Gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='ModifiedBy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
