# Generated by Django 3.1.7 on 2021-05-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0011_auto_20210322_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
