# Generated by Django 3.1.7 on 2021-05-25 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0014_auto_20210525_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='Active',
        ),
        migrations.RemoveField(
            model_name='account',
            name='CreatedDate',
        ),
        migrations.RemoveField(
            model_name='account',
            name='ModifiedDate',
        ),
    ]
